In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
data=load_digits()

In [4]:
x=data.data

In [5]:
y=data.target

In [6]:
x=pd.DataFrame(x)

In [7]:
y=pd.DataFrame(y)

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [11]:
Y_train.shape

(1437, 1)

In [41]:
svc1 = SVC(kernel="linear",gamma=20)  

In [42]:
svc1.fit(X_train,Y_train.values.reshape(1437))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=20, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
pred1 =svc1.predict(X_test)

In [44]:
accuracy_score(Y_test,pred1)

0.9805555555555555

In [45]:
print(classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        35
          1       0.95      1.00      0.98        41
          2       1.00      1.00      1.00        37
          3       1.00      0.97      0.98        33
          4       1.00      1.00      1.00        41
          5       0.97      0.97      0.97        35
          6       1.00      1.00      1.00        33
          7       1.00      0.97      0.99        35
          8       0.94      0.94      0.94        35
          9       0.94      0.94      0.94        35

avg / total       0.98      0.98      0.98       360



In [16]:
print(confusion_matrix(Y_test,pred1))

[[35  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  1]
 [ 0  0  0  0  0  0 33  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  2  0  0  0  0  0  0 33  0]
 [ 0  0  0  0  0  0  0  0  2 33]]


In [17]:
svc2 = SVC(kernel="poly")

In [18]:
svc2.fit(X_train,Y_train.values.reshape(1437))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
pred2 =svc2.predict(X_test)

In [20]:
accuracy_score(Y_test,pred2)

0.9916666666666667

In [21]:
print(classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        35
          1       0.98      1.00      0.99        41
          2       1.00      1.00      1.00        37
          3       1.00      1.00      1.00        33
          4       1.00      1.00      1.00        41
          5       0.97      1.00      0.99        35
          6       1.00      1.00      1.00        33
          7       1.00      0.97      0.99        35
          8       1.00      0.97      0.99        35
          9       0.97      0.97      0.97        35

avg / total       0.99      0.99      0.99       360



In [22]:
print(confusion_matrix(Y_test,pred2))

[[35  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 0  0 37  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  1  0  0  0  0  0  0 34  0]
 [ 0  0  0  0  0  1  0  0  0 34]]


In [23]:
svc3 = SVC(kernel="rbf")

In [24]:
svc3.fit(X_train,Y_train.values.reshape(1437))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
pred3 =svc3.predict(X_test)

In [26]:
accuracy_score(Y_test,pred3)

0.48055555555555557

In [27]:
print(classification_report(Y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.46      0.63        35
          1       1.00      0.29      0.45        41
          2       1.00      0.43      0.60        37
          3       0.15      1.00      0.26        33
          4       1.00      0.44      0.61        41
          5       1.00      0.77      0.87        35
          6       1.00      0.58      0.73        33
          7       1.00      0.49      0.65        35
          8       1.00      0.06      0.11        35
          9       1.00      0.37      0.54        35

avg / total       0.92      0.48      0.55       360



In [28]:
print(confusion_matrix(Y_test,pred3))

[[16  0  0 19  0  0  0  0  0  0]
 [ 0 12  0 29  0  0  0  0  0  0]
 [ 0  0 16 21  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0 23 18  0  0  0  0  0]
 [ 0  0  0  8  0 27  0  0  0  0]
 [ 0  0  0 14  0  0 19  0  0  0]
 [ 0  0  0 18  0  0  0 17  0  0]
 [ 0  0  0 33  0  0  0  0  2  0]
 [ 0  0  0 22  0  0  0  0  0 13]]


In [29]:
svc4 = SVC(kernel="sigmoid")

In [30]:
svc4.fit(X_train,Y_train.values.reshape(1437))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [31]:
pred4 =svc4.predict(X_test)

In [32]:
accuracy_score(Y_test,pred4)

0.09166666666666666

In [47]:
print(classification_report(Y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        35
          1       0.00      0.00      0.00        41
          2       0.00      0.00      0.00        37
          3       0.09      1.00      0.17        33
          4       0.00      0.00      0.00        41
          5       0.00      0.00      0.00        35
          6       0.00      0.00      0.00        33
          7       0.00      0.00      0.00        35
          8       0.00      0.00      0.00        35
          9       0.00      0.00      0.00        35

avg / total       0.01      0.09      0.02       360



C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
print(confusion_matrix(Y_test,pred4))

[[ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0  0  0]
 [ 0  0  0 37  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]]
