In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [46]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [8]:
df=load_digits()

In [9]:
x=df.data

In [10]:
y=df.target

In [11]:
x=pd.DataFrame(x)

In [12]:
y=pd.DataFrame(y)

In [17]:
x.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [19]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3)

In [20]:
reg=LogisticRegression()
reg.fit(X_train,Y_train)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
pred=reg.predict(X_test)

In [22]:
pred

array([6, 4, 4, 2, 7, 6, 5, 5, 9, 6, 2, 0, 5, 9, 7, 3, 2, 4, 4, 3, 2, 8,
       0, 0, 7, 5, 9, 5, 9, 6, 0, 9, 8, 4, 3, 0, 7, 4, 6, 8, 2, 2, 2, 9,
       1, 4, 2, 3, 2, 9, 4, 7, 1, 5, 7, 9, 7, 4, 2, 1, 7, 6, 8, 2, 5, 7,
       8, 0, 7, 9, 8, 7, 8, 2, 2, 3, 0, 7, 9, 6, 8, 6, 6, 2, 2, 7, 0, 5,
       7, 7, 3, 8, 0, 1, 6, 1, 9, 7, 2, 1, 1, 1, 2, 0, 6, 3, 9, 5, 3, 7,
       0, 1, 5, 5, 2, 3, 0, 1, 6, 2, 1, 0, 3, 4, 3, 4, 0, 9, 5, 4, 5, 3,
       0, 7, 7, 0, 8, 5, 0, 3, 9, 6, 1, 9, 1, 5, 2, 5, 2, 5, 6, 6, 4, 8,
       6, 1, 2, 8, 3, 6, 0, 7, 1, 0, 6, 2, 3, 0, 3, 3, 2, 4, 3, 7, 2, 0,
       0, 4, 2, 5, 8, 6, 1, 1, 9, 2, 3, 8, 4, 5, 2, 9, 5, 3, 6, 4, 6, 8,
       6, 8, 5, 5, 0, 1, 5, 1, 1, 0, 1, 5, 5, 9, 7, 1, 3, 1, 5, 2, 8, 8,
       2, 6, 5, 3, 1, 4, 0, 0, 6, 3, 1, 2, 0, 5, 1, 8, 7, 5, 9, 9, 1, 1,
       1, 6, 4, 1, 7, 2, 5, 0, 7, 1, 1, 7, 7, 2, 4, 3, 8, 0, 8, 9, 0, 8,
       6, 8, 7, 3, 7, 4, 8, 4, 9, 9, 8, 6, 8, 8, 7, 2, 0, 0, 0, 7, 1, 7,
       7, 0, 2, 0, 5, 5, 0, 7, 4, 0, 4, 1, 7, 0, 6,

In [23]:
reg.coef_

array([[ 0.00000000e+00, -5.50450345e-02, -1.28324646e-02,
         5.34582722e-02, -6.36958143e-02, -3.42045641e-01,
        -2.59965340e-01, -2.61197563e-02, -6.89845972e-06,
        -1.95427275e-01, -2.82897817e-03,  1.66621801e-01,
         1.87906392e-01,  2.73085146e-01, -3.57928620e-02,
        -3.99609260e-02, -2.82819127e-03,  3.26901148e-02,
         2.00072397e-01, -2.65372877e-02, -4.32794307e-01,
         3.02948098e-01, -2.17618307e-02, -7.57727008e-03,
        -1.41175546e-03,  2.72939043e-02, -3.97726692e-02,
        -1.54402110e-01, -6.29767789e-01,  1.11320358e-02,
         4.48232263e-02, -2.05687419e-04,  0.00000000e+00,
         2.27710425e-01,  1.30239982e-01, -1.36617826e-01,
        -6.06844736e-01, -4.11637078e-02, -7.82915677e-02,
         0.00000000e+00, -1.83168695e-03, -4.71853550e-02,
         2.03284488e-01, -2.95936220e-01, -2.42716402e-01,
        -6.96080512e-03,  1.24664198e-01, -8.13019935e-05,
        -1.60587471e-03, -1.38088925e-01,  2.04203481e-0

In [24]:
reg.intercept_

array([-0.02102668, -0.87747795, -0.03181366, -0.26051518,  0.01580873,
       -0.06530717, -0.06166973, -0.01567089, -2.51328893, -0.65314829])

### classification accuracy

In [28]:
reg.score(X_test,Y_test)

0.9555555555555556

### kfold

In [30]:
KFold= model_selection.KFold(n_splits=10, random_state=7)

### logarithmatic loss

In [32]:
results=model_selection.cross_val_score(reg,x,y,cv=KFold,scoring='neg_log_loss')

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [33]:
results

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

#### R2 metrices

In [34]:
res=model_selection.cross_val_score(reg,x,y,cv=KFold,scoring='r2')

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [35]:
res

array([0.73184699, 0.86942354, 0.81023661, 0.79423609, 0.82434177,
       0.94343263, 0.92524112, 0.90725247, 0.60169024, 0.82555495])

### Mean absolute error

In [39]:
a=LinearRegression()
a.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
pre=a.predict(X_train)

In [44]:
pre

array([[4.6025309 ],
       [7.86041776],
       [8.42083315],
       ...,
       [5.58213033],
       [5.8222989 ],
       [6.74600691]])

In [45]:
mean_absolute_error(Y_train,pre)

1.4339586134682252

### Mean squared error

In [48]:
mean_squared_error(Y_train, pre)

3.275194088323122

### Confusion matrix

In [37]:
print(confusion_matrix(Y_test,pred))

[[60  0  0  0  0  1  0  0  0  0]
 [ 0 43  0  1  0  0  1  0  5  1]
 [ 0  0 58  1  0  0  0  0  1  0]
 [ 0  0  0 54  0  1  0  0  0  0]
 [ 0  3  0  0 51  0  0  0  0  0]
 [ 0  0  0  0  0 51  0  0  0  0]
 [ 0  0  0  0  0  0 49  0  0  0]
 [ 0  0  0  0  0  0  0 62  0  0]
 [ 0  5  0  1  0  0  0  0 46  0]
 [ 0  0  0  0  0  0  0  0  3 42]]


### classification report

In [41]:
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        61
          1       0.84      0.84      0.84        51
          2       1.00      0.97      0.98        60
          3       0.95      0.98      0.96        55
          4       1.00      0.94      0.97        54
          5       0.96      1.00      0.98        51
          6       0.98      1.00      0.99        49
          7       1.00      1.00      1.00        62
          8       0.84      0.88      0.86        52
          9       0.98      0.93      0.95        45

avg / total       0.96      0.96      0.96       540

