In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [4]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [5]:
data=load_digits()

In [6]:
x=data.data

In [7]:
y=data.target

In [8]:
x=pd.DataFrame(x)

In [9]:
y=pd.DataFrame(y)

In [10]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [11]:
svc1 = SVC(kernel="linear")

In [12]:
svc1.fit(X_train,Y_train)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
pred1 =svc1.predict(X_test)

In [15]:
accuracy_score(Y_test,pred1)

0.975

In [16]:
print(classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        36
          1       0.95      1.00      0.98        40
          2       0.94      1.00      0.97        33
          3       1.00      0.91      0.96        35
          4       1.00      1.00      1.00        29
          5       0.96      0.98      0.97        45
          6       1.00      1.00      1.00        36
          7       0.97      1.00      0.98        32
          8       1.00      0.89      0.94        36
          9       0.95      0.97      0.96        38

avg / total       0.98      0.97      0.97       360



In [38]:
print(confusion_matrix(Y_test,pred1))

[[36  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  1 32  0  0  0  1  0  1]
 [ 0  0  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0  1]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 32  0  0]
 [ 0  2  1  0  0  1  0  0 32  0]
 [ 0  0  0  0  0  1  0  0  0 37]]


In [18]:
svc2 = SVC(kernel="poly")

In [22]:
svc2.fit(X_train,Y_train)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
pred2 =svc2.predict(X_test)

In [24]:
accuracy_score(Y_test,pred2)

0.9916666666666667

In [25]:
print(classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        36
          1       1.00      1.00      1.00        40
          2       0.97      1.00      0.99        33
          3       1.00      0.97      0.99        35
          4       1.00      1.00      1.00        29
          5       0.98      0.98      0.98        45
          6       1.00      1.00      1.00        36
          7       1.00      1.00      1.00        32
          8       1.00      1.00      1.00        36
          9       0.97      0.97      0.97        38

avg / total       0.99      0.99      0.99       360



In [39]:
print(confusion_matrix(Y_test,pred2))

[[36  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  1 34  0  0  0  0  0  0]
 [ 0  0  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0  1]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 32  0  0]
 [ 0  0  0  0  0  0  0  0 36  0]
 [ 0  0  0  0  0  1  0  0  0 37]]


In [26]:
svc3 = SVC(kernel="rbf")

In [27]:
svc3.fit(X_train,Y_train)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
pred3 =svc3.predict(X_test)

In [29]:
accuracy_score(Y_test,pred3)

0.525

In [30]:
print(classification_report(Y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.47      0.64        36
          1       1.00      0.53      0.69        40
          2       1.00      0.52      0.68        33
          3       0.17      1.00      0.29        35
          4       1.00      0.93      0.96        29
          5       1.00      0.27      0.42        45
          6       1.00      0.58      0.74        36
          7       1.00      0.81      0.90        32
          8       1.00      0.03      0.05        36
          9       1.00      0.32      0.48        38

avg / total       0.92      0.53      0.57       360



In [40]:
print(confusion_matrix(Y_test,pred3))

[[17  0  0 19  0  0  0  0  0  0]
 [ 0 21  0 19  0  0  0  0  0  0]
 [ 0  0 17 16  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0  2 27  0  0  0  0  0]
 [ 0  0  0 33  0 12  0  0  0  0]
 [ 0  0  0 15  0  0 21  0  0  0]
 [ 0  0  0  6  0  0  0 26  0  0]
 [ 0  0  0 35  0  0  0  0  1  0]
 [ 0  0  0 26  0  0  0  0  0 12]]


In [32]:
svc4 = SVC(kernel="sigmoid")

In [33]:
svc4.fit(X_train,Y_train)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
pred4 =svc4.predict(X_test)

In [36]:
accuracy_score(Y_test,pred4)

0.08055555555555556

In [37]:
print(classification_report(Y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        36
          1       0.00      0.00      0.00        40
          2       0.00      0.00      0.00        33
          3       0.00      0.00      0.00        35
          4       0.08      1.00      0.15        29
          5       0.00      0.00      0.00        45
          6       0.00      0.00      0.00        36
          7       0.00      0.00      0.00        32
          8       0.00      0.00      0.00        36
          9       0.00      0.00      0.00        38

avg / total       0.01      0.08      0.01       360



C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [41]:
print(confusion_matrix(Y_test,pred4))

[[ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0 40  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0]
 [ 0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0 29  0  0  0  0  0]
 [ 0  0  0  0 45  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0 32  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]]
