### Question 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [25]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [6]:
data = load_iris()

In [7]:
x=data.data

In [8]:
y=data.target

In [9]:
x=pd.DataFrame(x)

In [10]:
y=pd.DataFrame(y)

In [40]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)

In [42]:
Y_train.shape

(120, 1)

In [41]:
model=GaussianNB()

In [43]:
model.fit(X_train,Y_train.values.reshape(120))

GaussianNB(priors=None)

In [44]:
pred=model.predict(X_test)

In [45]:
model.score(X_test,Y_test)

0.9666666666666667

In [46]:
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.91      1.00      0.95        10
          2       1.00      0.92      0.96        12

avg / total       0.97      0.97      0.97        30



In [47]:
print(confusion_matrix(Y_test,pred))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]


In [48]:
model1=MultinomialNB()

In [54]:
model1.fit(X_train,Y_train.values.reshape(120))

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [55]:
pre=model1.predict(X_test)

In [56]:
model1.score(X_test,Y_test)

0.8666666666666667

In [57]:
print(classification_report(Y_test,pre))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         8
          1       0.71      1.00      0.83        10
          2       1.00      0.67      0.80        12

avg / total       0.90      0.87      0.86        30



In [58]:
print(confusion_matrix(Y_test,pre))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  4  8]]


### question 1

In [20]:
A=9/14  ##P(y)
B=5/14  ###P(sunny)
C=3/9 ###P(sunny|y)
P=(C*A)/B


In [21]:
P

0.6