In [53]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

In [2]:
data = load_wine()

In [3]:
x = data.data
y = data.target

In [47]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.25)

In [48]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [49]:
bag = BaggingClassifier(base_estimator= model , max_samples= 0.6 )

In [50]:
bag.fit(X_train,Y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=0.6, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [51]:
pred1 = bag.predict(X_test)

In [75]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pred1)*100)
print("Classification Report\n")
print(classification_report(Y_test,pred1))
print("Confusion Matrix")
print(confusion_matrix(Y_test,pred1))

Accuracy Score:

97.77777777777777
Classification Report

             precision    recall  f1-score   support

          0       1.00      0.94      0.97        18
          1       0.94      1.00      0.97        16
          2       1.00      1.00      1.00        11

avg / total       0.98      0.98      0.98        45

Confusion Matrix
[[17  1  0]
 [ 0 16  0]
 [ 0  0 11]]


In [59]:
from sklearn.ensemble import GradientBoostingClassifier

In [60]:
model2 = GradientBoostingClassifier(n_estimators=100,learning_rate=1.0,max_depth=1)

In [61]:
model2.fit(X_train,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=1.0, loss='deviance', max_depth=1,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [62]:
pred2 = model2.predict(X_test)

In [76]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pred2)*100)
print("Classification Report\n")
print(classification_report(Y_test,pred2))
print("Confusion Matrix")
print(confusion_matrix(Y_test,pred2))

Accuracy Score:

100.0
Classification Report

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        18
          1       1.00      1.00      1.00        16
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45

Confusion Matrix
[[18  0  0]
 [ 0 16  0]
 [ 0  0 11]]


In [64]:
from sklearn.ensemble import RandomForestClassifier

In [65]:
model3 = RandomForestClassifier()

In [66]:
model3.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [67]:
pred3 = model3.predict(X_test)

In [77]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pred3)*100)
print("Classification Report\n")
print(classification_report(Y_test,pred3))
print("Confusion Matrix")
print(confusion_matrix(Y_test,pred3))

Accuracy Score:

100.0
Classification Report

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        18
          1       1.00      1.00      1.00        16
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        45

Confusion Matrix
[[18  0  0]
 [ 0 16  0]
 [ 0  0 11]]


In [69]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [70]:
model4 = DecisionTreeClassifier()
model5 = LogisticRegression()
model6 = SVC()

In [71]:
new_model = VotingClassifier(estimators=[('DT',model4),('LR',model5),('SVC',model6)])

In [72]:
new_model.fit(X_train,Y_train)

VotingClassifier(estimators=[('DT', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [73]:
pre = new_model.predict(X_test)

C:\Users\Shivam\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [78]:
print("Accuracy Score:\n")
print(metrics.accuracy_score(Y_test,pre)*100)
print("Classification Report\n")
print(classification_report(Y_test,pre))
print("Confusion Matrix")
print(confusion_matrix(Y_test,pre))

Accuracy Score:

93.33333333333333
Classification Report

             precision    recall  f1-score   support

          0       1.00      0.89      0.94        18
          1       0.84      1.00      0.91        16
          2       1.00      0.91      0.95        11

avg / total       0.94      0.93      0.93        45

Confusion Matrix
[[16  2  0]
 [ 0 16  0]
 [ 0  1 10]]
